spring:
  profiles:
    group:
      "local": "local,common"
      "dev":  "dev,common"
      "prod": "prod,common"

---

spring:
  config:
    activate:
      on-profile: "common"
      
  lifecycle:
    timeout-per-shutdown-phase: 30s
    
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*
    
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    static-path-pattern: /static/**
      
server:
  port: 8081
  shutdown: graceful

  servlet:
    session:
      timeout: 120m
      
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
jasypt:
  encryptor:
    #bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
      
---
      
spring:
  config:
    activate:
      on-profile: "local"
    
  datasource1:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: ENC(DWKsmBz/S+wB6b/YI5ZDYdKfSvto0qvvfDNipUdsTfSrybgLZkzRo2w8N4s52mwj7mTCEvKBCy1bYGEEft8/SRcHPl5JLP+4xHXjVKV9K1Vp2WBHL2TWa7ZvzEyajjnH)
    username: ENC(kNlVgvfcdBcMj/bo0FXONkXH26eW42NB)
    password: ENC(ISkaG5TENa8AG08cbcAZl46aCcSaiN6T10GU7kgvK78=)
    
  datasource2:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: ENC(lbev09K62wfWB4gPZuxVBzdgG4WVN5vB8Uru7jhweYq4/qU1L05JHB6mGBnV9B1d7v63Ak9CM5g=)
    username: ENC(qTbbqN2iMpvPD6PPfQeELA==)
    password: ENC(nDW5tU9l95j7PBy1d+JW/A==)
    
  devtools:
    livereload:
        enabled: true
    
props:
  devMode: LOCAL
  realgridLic: realgridjs-lic
  realgridjs: realgridjs_eval.1.1.39.min
  realgridapi: realgridjs-api.1.1.39
  SERVER_FILE_PATH: D:\\myproject\\upload
  SERVER_FILE_MAX: 52428800
  PDF_FILE_PATH: D:\\myproject\\pdf
  WEB_PATH: http://52.231.187.60:8081
  PDF_VIEWER: /pdfjs/web/viewer.html
  
---
      
spring:
  config:
    activate:
      on-profile: "dev"
    
  datasource1:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: ENC(DWKsmBz/S+wB6b/YI5ZDYdKfSvto0qvvfDNipUdsTfSrybgLZkzRo2w8N4s52mwj7mTCEvKBCy1bYGEEft8/SRcHPl5JLP+4xHXjVKV9K1Vp2WBHL2TWa7ZvzEyajjnH)
    username: ENC(kNlVgvfcdBcMj/bo0FXONkXH26eW42NB)
    password: ENC(ISkaG5TENa8AG08cbcAZl46aCcSaiN6T10GU7kgvK78=)
    
  datasource2:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: ENC(lbev09K62wfWB4gPZuxVBzdgG4WVN5vB8Uru7jhweYq4/qU1L05JHB6mGBnV9B1d7v63Ak9CM5g=)
    username: ENC(qTbbqN2iMpvPD6PPfQeELA==)
    password: ENC(nDW5tU9l95j7PBy1d+JW/A==)
    
props:
  devMode: DEV
  realgridLic: realgridjs-lic
  realgridjs: realgridjs_eval.1.1.39.min
  realgridapi: realgridjs-api.1.1.39
  SERVER_FILE_PATH: /home/wonikadmin/system_attach/snop_dev/upload
  SERVER_FILE_MAX: 52428800
  PDF_FILE_PATH: /home/wonikadmin/system_attach/snop_dev/pdf
  WEB_PATH: https://snop-test.wonikqnc.com
  PDF_VIEWER: /pdfjs/web/viewer.html
  
---
      
spring:
  config:
    activate:
      on-profile: "prod"
    
  datasource1:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: ENC(GL/wpGAN6KSfoHIuov0bTkyCm9wHPxIYW4oS2i3B5aVjstmoD/y67PpPL7rBl0R9w+/zDSQpYV4ILEfyZrGBuh8CnV7/2ihqDW4gFLhj5A9Cr4NxSxnYMooq3aaWD22D)
    username: ENC(xWPlnWT19WjF9LBO9HR8B7+cdFj7EOeq)
    password: ENC(JfbgUUoGHBxhcjA6HXlFslQ0P833e5HTxJf7G7v9fcQ=)
    
  datasource2:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: ENC(lbev09K62wfWB4gPZuxVBzdgG4WVN5vB8Uru7jhweYq4/qU1L05JHB6mGBnV9B1d7v63Ak9CM5g=)
    username: ENC(qTbbqN2iMpvPD6PPfQeELA==)
    password: ENC(nDW5tU9l95j7PBy1d+JW/A==)
    
props:
  devMode: REAL
  realgridLic: realgridjs-lic
  realgridjs: realgridjs_eval.1.1.39.min
  realgridapi: realgridjs-api.1.1.39
  SERVER_FILE_PATH: /home/wonikadmin/system_attach/snop_dev/upload
  SERVER_FILE_MAX: 52428800
  PDF_FILE_PATH: /home/wonikadmin/system_attach/snop_dev/pdf
  WEB_PATH: https://snop-test.wonikqnc.com
  PDF_VIEWER: /pdfjs/web/viewer.html

